<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>NexGen.MediatR.Extensions.Caching.EntityFramework</Title>
    <Description>Entity Framework Core ChangeTracker auto-eviction for NexGen.MediatR.Extensions.Caching.</Description>
    <PackageTags>Mediator;MediatR;Caching;Cache;Redis;MemoryCache;EF;EFCore;EntityFramework;Extensions;CQRS;MessageBus;EventBus;InMemoryCache;DistributedCache;AsyncMessaging;CommandHandler;QueryHandler;PubSub;DataCaching;CacheProvider;HighPerformanceCaching;ThreadSafeCache;DatabaseCaching;ORM;LINQ;EFExtensions;EntityFrameworkCoreExtensions</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NexGen.MediatR.Extensions.Caching\NexGen.MediatR.Extensions.Caching.csproj" />
  </ItemGroup>

</Project>
